# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - anna-net

  
#  backend:
#    build: ./backend
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
#      SPRING_DATASOURCE_USERNAME: ${DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#    depends_on:
#      - postgres
#    ports:
#      - "${BACKEND_PORT:-8080}:8080"
#    networks:
#      - anna-net
  
#  frontend:
#    build: ./frontend
#    environment:
#      - REACT_APP_API_URL=${API_URL:-http://localhost:8080}
#    ports:
#      - "${FRONTEND_PORT:-3000}:3000"
#    depends_on:
#      - backend
#    networks:
#      - anna-net

volumes:
  postgres_data:

networks:
  anna-net:
    driver: bridge