package com.annapurna.service;

import com.annapurna.dto.*;
import com.annapurna.exception.CustomerNotFoundException;
import com.annapurna.exception.MenuItemNotFoundException;
import com.annapurna.model.*;
import com.annapurna.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Transactional
public class OrderService {
    
    private final OrderHeaderRepository orderHeaderRepository;
    private final OrderLineRepository orderLineRepository;
    private final FoodMstRepository foodMstRepository;
    private final CostSheetRepository costSheetRepository;
    private final CustomerPersonAccRepository customerRepository;
    private final CustomerOrderHistRepository custOrderHistRepository;
    
    public Integer createOrder(CreateOrderRequest request) {
        // Validation: Walk-in customers cannot defer payment
        if (request.getCustomerId() == null && Boolean.TRUE.equals(request.getIsDeferred())) {
            throw new IllegalArgumentException("Walk-in customers cannot defer payment");
        }
        
        OrderHeader orderHeader = new OrderHeader();
        orderHeader.setWhoGaveOrder(request.getWhoGaveOrder());
        orderHeader.setIsDeferred(request.getIsDeferred());
        orderHeader.setIsPaidFull(request.getIsPaidFull());
        
        // Handle known customer
        if (request.getCustomerId() != null) {
            CustomerPersonAcc customer = customerRepository.findById(request.getCustomerId())
                .orElseThrow(() -> new CustomerNotFoundException("Customer not found: " + request.getCustomerId()));
            orderHeader.setCustomer(customer);
            orderHeader.setIsKnownCustomer(true);
        } else {
            // Walk-in customer defaults
            orderHeader.setIsDeferred(false);
            orderHeader.setIsPaidFull(true);
        }
        
        // Save header first (generates order_number via trigger)
        orderHeader = orderHeaderRepository.save(orderHeader);
        
        List<OrderLine> orderLines = new ArrayList<>();
        BigDecimal totalOrderAmount = BigDecimal.ZERO;
        
        // Process order items
        for (OrderItemRequest itemRequest : request.getItems()) {
            FoodMst foodItem = findFoodItem(itemRequest);
            
            CostSheet costSheet = costSheetRepository.findActiveCostForItem(foodItem.getItemId())
                .orElseThrow(() -> new MenuItemNotFoundException("Active cost not found for item: " + foodItem.getItemCode()));
            
            OrderLine orderLine = new OrderLine();
            orderLine.setOrderHeader(orderHeader);
            orderLine.setFoodMst(foodItem);
            orderLine.setQuantity(itemRequest.getQuantity());
            orderLine.setCostPerItem(costSheet.getCost());
            orderLine.setIsPaid(Boolean.TRUE.equals(request.getIsPaidFull()));
            orderLine.calculateTotalCost();
            
            orderLines.add(orderLine);
            totalOrderAmount = totalOrderAmount.add(orderLine.getTotalCost());
        }
        
        // Save all order lines (line_number generated by trigger)
        orderLines = orderLineRepository.saveAll(orderLines);
        
        // Create customer order history for deferred payments
        if (Boolean.TRUE.equals(orderHeader.getIsDeferred()) && orderHeader.getCustomer() != null) {
            for (OrderLine line : orderLines) {
                CustomerOrderHist hist = new CustomerOrderHist();
                hist.setCustomer(orderHeader.getCustomer());
                hist.setOrderLine(line);
                hist.setIsPaidNow(false);
                custOrderHistRepository.save(hist);
            }
            
            // Update customer total due
            CustomerPersonAcc customer = orderHeader.getCustomer();
            customer.setTotalDue(customer.getTotalDue().add(totalOrderAmount));
            customerRepository.save(customer);
        }
        
        // Update order header with total
        orderHeader.setTotalDue(totalOrderAmount);
        orderHeaderRepository.save(orderHeader);
        
        return orderHeader.getHeaderId();
    }
    
    private FoodMst findFoodItem(OrderItemRequest request) {
        if (request.getItemNumber() != null) {
            return foodMstRepository.findByItemNumberAndInUseTrue(request.getItemNumber())
                .orElseThrow(() -> new MenuItemNotFoundException("Food item not found: " + request.getItemNumber()));
        } else if (request.getItemCode() != null) {
            return foodMstRepository.findByItemCodeAndInUseTrue(request.getItemCode())
                .orElseThrow(() -> new MenuItemNotFoundException("Food item not found: " + request.getItemCode()));
        } else {
            throw new IllegalArgumentException("Either itemCode or itemNumber must be provided");
        }
    }
    
    @Transactional(readOnly = true)
    public List<PendingOrderResponse> getUnservedOrders() {
        return orderLineRepository.getUnservedOrders();
    }
    
    public void markItemsAsServed(List<Integer> lineIds, String servedBy) {
        orderLineRepository.markItemsAsServed(lineIds, LocalDateTime.now(), servedBy);
    }
    
    @Transactional(readOnly = true)
    public OrderResponse getOrderByNumber(Long orderNumber) {
        OrderHeader header = orderHeaderRepository.findByOrderNumber(orderNumber)
            .orElseThrow(() -> new IllegalArgumentException("Order not found: " + orderNumber));
        
        return mapToOrderResponse(header);
    }
    
    @Transactional(readOnly = true)
    public OrderResponse getOrderById(Integer headerId) {
        OrderHeader header = orderHeaderRepository.findById(headerId)
            .orElseThrow(() -> new IllegalArgumentException("Order not found: " + headerId));
        
        return mapToOrderResponse(header);
    }
    
    private OrderResponse mapToOrderResponse(OrderHeader header) {
        List<OrderLine> lines = orderLineRepository.findByHeaderId(header.getHeaderId());
        
        List<OrderLineResponse> lineResponses = lines.stream()
            .map(line -> new OrderLineResponse(
                line.getLineId(),
                line.getLineNumber(),
                line.getFoodMst().getItemCode(),
                line.getFoodMst().getItemNumber(),
                line.getFoodMst().getItemDescription(),
                line.getQuantity(),
                line.getCostPerItem(),
                line.getTotalCost(),
                line.getIsPaid(),
                line.getIsServed()
            ))
            .collect(Collectors.toList());
        
        return new OrderResponse(
            header.getHeaderId(),
            header.getOrderNumber(),
            header.getCreationDate(),
            header.getWhoGaveOrder(),
            header.getCustomer() != null ? header.getCustomer().getName() : "Walk-in",
            header.getCustomer() != null ? header.getCustomer().getCustomerId() : null,
            header.getIsPaidFull(),
            header.getIsDeferred(),
            header.getTotalDue(),
            lineResponses
        );
    }
}