--------------------------------------------------------------------------------
-- ANNAPURNA CANTEEN DB - FOO MODULE (Menu / Food Master)
-- Run order: 01_foo -> 02_cust -> 03_om -> 04_billing -> 05_audit -> 06_procedures
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1: Sequences
--------------------------------------------------------------------------------
CREATE SEQUENCE FOO_FOOD_MST_SEQ   START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;
CREATE SEQUENCE FOO_COST_SHEET_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;


--------------------------------------------------------------------------------
-- 2: Tables
-- DEPENDS ON- 1: Sequences
--------------------------------------------------------------------------------

-- FOO_FOOD_MST: Menu Items Master
CREATE TABLE FOO_FOOD_MST_TBL (
    ITEM_ID           NUMBER(10)      DEFAULT FOO_FOOD_MST_SEQ.NEXTVAL PRIMARY KEY,
    ITEM_CODE         VARCHAR2(20)    NOT NULL,
    ITEM_NUMBER       NUMBER(4)       NOT NULL,
    ITEM_DESCRIPTION  VARCHAR2(255)   NOT NULL,
    CATEGORY_CODE     VARCHAR2(20),                     -- NEW: replaces magic-digit parsing of item_number
    CREATION_DATE     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY        VARCHAR2(100)   DEFAULT 'SYSTEM',
    UPDATED_DATE      TIMESTAMP,
    UPDATED_BY        VARCHAR2(100),
    IN_USE            NUMBER(1)       DEFAULT 1 NOT NULL,
    VERSION_NO        NUMBER(10)      DEFAULT 0 NOT NULL,
    CONSTRAINT UQ_FOOD_MST_CODE   UNIQUE (ITEM_CODE),
    CONSTRAINT UQ_FOOD_MST_NUMBER UNIQUE (ITEM_NUMBER),
    CONSTRAINT CHK_FOOD_IN_USE    CHECK (IN_USE IN (0,1)),
    CONSTRAINT CHK_ITEM_NUMBER    CHECK (ITEM_NUMBER BETWEEN 1000 AND 5999)
);

COMMENT ON COLUMN FOO_FOOD_MST_TBL.ITEM_NUMBER IS '4-digit code: 1st=category(1-5), 2nd=type(1-2), 3rd-4th=item(00-99)';

-- FOO_COST_SHEET: Item Pricing with History
CREATE TABLE FOO_COST_SHEET_TBL (
    COST_ID         NUMBER(10)    DEFAULT FOO_COST_SHEET_SEQ.NEXTVAL PRIMARY KEY,
    ITEM_ID         NUMBER(10)    NOT NULL,
    COST            NUMBER(10,2)  NOT NULL,
    IS_ACTIVE       NUMBER(1)     DEFAULT 1 NOT NULL,
    CREATION_DATE   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    INACTIVE_DATE   TIMESTAMP,
    CREATED_BY      VARCHAR2(100) DEFAULT 'SYSTEM',
    -- virtual column emulates PG's partial unique index (WHERE is_active = TRUE)
    ACTIVE_ITEM_ID  NUMBER(10) GENERATED ALWAYS AS (CASE WHEN IS_ACTIVE = 1 THEN ITEM_ID END) VIRTUAL,
    CONSTRAINT FK_COST_SHEET_ITEM FOREIGN KEY (ITEM_ID) REFERENCES FOO_FOOD_MST_TBL(ITEM_ID),
    CONSTRAINT CHK_COST_POSITIVE  CHECK (COST > 0),
    CONSTRAINT CHK_COST_ACTIVE    CHECK (IS_ACTIVE IN (0,1))
);

CREATE UNIQUE INDEX FOO_UQ_ACTIVE_COST_PER_ITEM ON FOO_COST_SHEET_TBL (ACTIVE_ITEM_ID);


--------------------------------------------------------------------------------
-- 3: Triggers
-- DEPENDS ON- 2: Tables
--------------------------------------------------------------------------------

-- Auto-deactivate old cost sheets when a new active one is inserted/updated
CREATE OR REPLACE TRIGGER FOO_DEACTIVATE_OLD_COST_TRG
    BEFORE INSERT OR UPDATE ON FOO_COST_SHEET_TBL
    FOR EACH ROW
    WHEN (NEW.IS_ACTIVE = 1)
BEGIN
    UPDATE FOO_COST_SHEET_TBL
       SET IS_ACTIVE = 0,
           INACTIVE_DATE = SYSTIMESTAMP
     WHERE ITEM_ID = :NEW.ITEM_ID
       AND IS_ACTIVE = 1
       AND COST_ID != NVL(:NEW.COST_ID, -1);
END;
/

CREATE OR REPLACE TRIGGER FOO_PREVENT_MANUAL_ITEM_ID_TRG
    BEFORE INSERT ON FOO_FOOD_MST_TBL
    FOR EACH ROW
BEGIN
    IF :NEW.ITEM_ID IS NOT NULL AND :NEW.ITEM_ID != FOO_FOOD_MST_SEQ.CURRVAL THEN
        RAISE_APPLICATION_ERROR(-20003, 'Cannot manually set item_id. It must be auto-generated.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -8002 THEN --CURRVAL NOT DEFINED IN SESSION
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE TRIGGER FOO_PREVENT_MANUAL_COST_ID_TRG
    BEFORE INSERT ON FOO_COST_SHEET_TBL
    FOR EACH ROW
BEGIN
    IF :NEW.COST_ID IS NOT NULL AND :NEW.COST_ID != FOO_COST_SHEET_SEQ.CURRVAL THEN
        RAISE_APPLICATION_ERROR(-20003, "CANNOT MANUALLY SET COST_ID. IT MUST BE AUTO-GENERATED.");
    END IF; 
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -8002 THEN --CURRVAL NOT DEFINED IN SESSION
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/

--------------------------------------------------------------------------------
-- 4: Views
-- DEPENDS ON- 2: Tables
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW FOO_ACTIVE_MENU_V AS
SELECT  F.ITEM_ID,  F.ITEM_CODE, 
        F.ITEM_NUMBER, F.ITEM_DESCRIPTION, F.CATEGORY_CODE, C.COST
FROM FOO_FOOD_MST_TBL F, FOO_COST_SHEET_TBL C 
WHERE F.ITEM_ID = C.ITEM_ID 
    AND C.IS_ACTIVE = 1
    AND F.IN_USE = 1;

CREATE OR REPLACE VIEW FOO_COST_HISTORY_V AS
SELECT  C.COST_ID, F.ITEM_CODE, F.ITEM_DESCRIPTION, 
        C.COST, C.IS_ACTIVE, C.CREATION_DATE, C.INACTIVE_DATE
FROM FOO_COST_SHEET_TBL C, FOO_FOOD_MST_TBL F
WHERE F.ITEM_ID = C.ITEM_ID
ORDER BY F.ITEM_CODE, C.CREATION_DATE DESC;
--------------------------------------------------------------------------------
-- MODULE: FOO (Menu / Food Master)
-- FILE:   05_sample_data.sql
-- DEPENDS ON: 02_tables.sql, 03_triggers.sql
--------------------------------------------------------------------------------

INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('B01', 1101, 'Idli', 'BREAKFAST');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('B02', 1102, 'Dosa', 'BREAKFAST');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('B03', 1103, 'Poha', 'BREAKFAST');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('B04', 1104, 'Upma', 'BREAKFAST');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('B05', 1105, 'Paratha', 'BREAKFAST');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('B06', 1201, 'Egg Omelette', 'BREAKFAST');

INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('L01', 2101, 'Dal Rice', 'LUNCH');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('L02', 2102, 'Roti Sabji', 'LUNCH');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('L03', 2103, 'Chole Bhature', 'LUNCH');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('L04', 2104, 'Paneer Curry', 'LUNCH');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('L05', 2201, 'Chicken Biryani', 'LUNCH');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('L06', 2202, 'Chicken Tikka', 'LUNCH');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('L07', 2203, 'Fish Curry', 'LUNCH');

INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('S01', 3101, 'Samosa', 'SNACKS');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('S02', 3102, 'Sandwich', 'SNACKS');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('S03', 3103, 'Pakora', 'SNACKS');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('S04', 3104, 'Biscuits', 'SNACKS');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('S05', 3201, 'Chicken Roll', 'SNACKS');

INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('BV01', 4101, 'Tea', 'BEVERAGES');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('BV02', 4102, 'Coffee', 'BEVERAGES');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('BV03', 4103, 'Cold Drink', 'BEVERAGES');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('BV04', 4104, 'Lassi', 'BEVERAGES');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('BV05', 4105, 'Juice', 'BEVERAGES');

INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('D01', 5101, 'Gulab Jamun', 'DESSERTS');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('D02', 5102, 'Ice Cream', 'DESSERTS');
INSERT INTO FOO_FOOD_MST_TBL (ITEM_CODE, ITEM_NUMBER, ITEM_DESCRIPTION, CATEGORY_CODE) VALUES ('D03', 5103, 'Kheer', 'DESSERTS');

INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 30.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'B01';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 40.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'B02';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 35.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'B03';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 30.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'B04';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 40.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'B05';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 50.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'B06';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 60.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'L01';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 50.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'L02';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 80.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'L03';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 120.00 FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'L04';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 180.00 FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'L05';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 150.00 FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'L06';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 140.00 FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'L07';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 20.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'S01';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 40.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'S02';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 25.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'S03';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 10.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'S04';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 60.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'S05';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 10.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'BV01';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 15.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'BV02';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 25.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'BV03';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 30.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'BV04';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 35.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'BV05';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 40.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'D01';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 50.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'D02';
INSERT INTO FOO_COST_SHEET_TBL (ITEM_ID, COST) SELECT ITEM_ID, 45.00  FROM FOO_FOOD_MST_TBL WHERE ITEM_CODE = 'D03';

COMMIT;