--------------------------------------------------------------------------------
-- ANNAPURNA CANTEEN DB - CUST MODULE (Customer Master)
-- MODULE CODE: CUST   (derived from file name 02-CUST.sql)
-- Run order: 01-FOO -> 02-CUST -> 03-OM -> 04-BILL -> 05-AUDIT -> 06-RPT
--
-- NAMING: <MODULE>_<NAME>_<TYPE>   TBL SEQ TRG V PRC FUNC IDX
-- JOINS : WHERE-clause only. ANSI JOIN syntax is never used.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1: sequences
--------------------------------------------------------------------------------
CREATE SEQUENCE CUST_PERSON_ACC_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;


--------------------------------------------------------------------------------
-- 2: tables
-- DEPENDS ON- 1: sequences
--------------------------------------------------------------------------------
CREATE TABLE CUST_PERSON_ACC_TBL (
    customer_id      NUMBER(10)     DEFAULT CUST_PERSON_ACC_SEQ.NEXTVAL PRIMARY KEY,
    customer_number  VARCHAR2(50)   NOT NULL,
    name             VARCHAR2(255)  NOT NULL,
    phone            VARCHAR2(20),
    email            VARCHAR2(255),
    creation_date    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    created_by       VARCHAR2(100)  DEFAULT 'SYSTEM',
    updated_date     TIMESTAMP,
    updated_by       VARCHAR2(100),
    is_active        NUMBER(1)      DEFAULT 1 NOT NULL,
    total_due        NUMBER(10,2)   DEFAULT 0.00 NOT NULL,
    loyalty_points   NUMBER(10)     DEFAULT 0 NOT NULL,
    version_no       NUMBER(10)     DEFAULT 0 NOT NULL,
    CONSTRAINT uq_customer_number  UNIQUE (customer_number),
    CONSTRAINT chk_customer_active CHECK (is_active IN (0,1)),
    CONSTRAINT chk_total_due       CHECK (total_due >= 0)
);


--------------------------------------------------------------------------------
-- 3: indexes
-- DEPENDS ON- 2: tables
--------------------------------------------------------------------------------
CREATE INDEX CUST_PERSON_ACC_PHONE_IDX     ON CUST_PERSON_ACC_TBL (phone);
CREATE INDEX CUST_PERSON_ACC_ACTIVE_IDX    ON CUST_PERSON_ACC_TBL (is_active);
CREATE INDEX CUST_PERSON_ACC_TOTAL_DUE_IDX ON CUST_PERSON_ACC_TBL (total_due);


--------------------------------------------------------------------------------
-- 4: triggers
-- DEPENDS ON- 1: sequences, 2: tables
--------------------------------------------------------------------------------

-- Prevent manual customer_id insertion (sequence-only)
CREATE OR REPLACE TRIGGER CUST_PREVENT_MANUAL_CUST_ID_TRG
    BEFORE INSERT ON CUST_PERSON_ACC_TBL
    FOR EACH ROW
DECLARE
    v_currval NUMBER;
BEGIN
    IF :NEW.customer_id IS NOT NULL THEN
        BEGIN
            v_currval := CUST_PERSON_ACC_SEQ.CURRVAL;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE = -8002 THEN   -- CURRVAL not yet defined in this session
                    RETURN;
                END IF;
                RAISE;
        END;

        IF :NEW.customer_id != v_currval THEN
            RAISE_APPLICATION_ERROR(-20201,
                'Cannot manually set customer_id. It must be generated by CUST_PERSON_ACC_SEQ.');
        END IF;
    END IF;
END;
/

-- Maintain audit columns and optimistic-lock version on update
CREATE OR REPLACE TRIGGER CUST_PERSON_ACC_AUDIT_TRG
    BEFORE UPDATE ON CUST_PERSON_ACC_TBL
    FOR EACH ROW
BEGIN
    :NEW.updated_date := SYSTIMESTAMP;
    :NEW.version_no   := NVL(:OLD.version_no, 0) + 1;
END;
/


--------------------------------------------------------------------------------
-- 5: views
-- DEPENDS ON- 2: tables
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW CUST_CUSTOMER_DUES_V AS
SELECT customer_id, customer_number, name, phone, total_due
  FROM CUST_PERSON_ACC_TBL
 WHERE is_active = 1
   AND total_due > 0
 ORDER BY total_due DESC;

CREATE OR REPLACE VIEW CUST_ACTIVE_CUSTOMERS_V AS
SELECT customer_id, customer_number, name, phone, email, loyalty_points
  FROM CUST_PERSON_ACC_TBL
 WHERE is_active = 1
 ORDER BY name;


--------------------------------------------------------------------------------
-- 6: sample data
-- DEPENDS ON- 2: tables, 4: triggers
--------------------------------------------------------------------------------

INSERT INTO CUST_PERSON_ACC_TBL (customer_number, name, phone) VALUES ('CUST001', 'Rajesh Kumar', '9876543210');
INSERT INTO CUST_PERSON_ACC_TBL (customer_number, name, phone) VALUES ('CUST002', 'Priya Sharma', '9876543211');
INSERT INTO CUST_PERSON_ACC_TBL (customer_number, name, phone) VALUES ('CUST003', 'Amit Singh',  '9876543212');

COMMIT;