--------------------------------------------------------------------------------
-- ANNAPURNA CANTEEN DB - OM MODULE (Order Management)
-- Run order: 01_foo -> 02_cust -> 03_om -> 04_billing -> 05_audit -> 06_procedures
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1: sequences
--------------------------------------------------------------------------------
-- Business format YYMMDD + 3-digit daily sequence is generated by OM_GENERATE_ORDER_NUMBER_TRG;
-- this sequence only backs the surrogate header_id.
CREATE SEQUENCE OM_ORDER_HEADERS_SEQ
    START WITH 10000
    INCREMENT BY 1
    MINVALUE 10000
    MAXVALUE 9999999999
    NOCYCLE
    CACHE 20;

CREATE SEQUENCE OM_ORDER_LINES_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 20;

--------------------------------------------------------------------------------
-- 2: tables
-- DEPENDS ON- 1: sequences, FOO module (FOO_FOOD_MST), CUST module (CUST_PERSON_ACC)
--------------------------------------------------------------------------------
-- OM_ORDER_HEADERS: Order Headers
CREATE TABLE OM_ORDER_HEADERS (
    header_id          NUMBER(10)     DEFAULT OM_ORDER_HEADERS_SEQ.NEXTVAL PRIMARY KEY,
    order_number       NUMBER(18),
    creation_date      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    who_gave_order     VARCHAR2(255),
    when_ordered       TIMESTAMP      DEFAULT SYSTIMESTAMP,
    is_paid_full       NUMBER(1)      DEFAULT 0,
    is_deferred        NUMBER(1)      DEFAULT NULL,
    is_known_customer  NUMBER(1)      DEFAULT 0,
    customer_id        NUMBER(10),
    total_due          NUMBER(10,2)   DEFAULT 0.00,
    order_status       VARCHAR2(20)   DEFAULT 'PENDING',   -- NEW: PENDING/COMPLETED/CANCELLED
    table_no           VARCHAR2(20),                       -- NEW: dine-in/parcel identifier
    CONSTRAINT uq_order_number UNIQUE (order_number),
    CONSTRAINT fk_order_header_customer FOREIGN KEY (customer_id) REFERENCES CUST_PERSON_ACC(customer_id),
    CONSTRAINT chk_paid_full   CHECK (is_paid_full IN (0,1)),
    CONSTRAINT chk_deferred    CHECK (is_deferred IN (0,1)),
    CONSTRAINT chk_known_cust  CHECK (is_known_customer IN (0,1)),
    CONSTRAINT chk_payment_deferred CHECK (
        (is_paid_full = 1 AND is_deferred = 0) OR
        (is_paid_full = 0 AND is_deferred = 1) OR
        (is_paid_full IS NULL OR is_deferred IS NULL)
    ),
    CONSTRAINT chk_walk_in_payment CHECK (
        (customer_id IS NULL AND is_known_customer = 0 AND
         (is_deferred IS NULL OR is_deferred = 0) AND is_paid_full = 1) OR
        (customer_id IS NOT NULL)
    )
);

COMMENT ON COLUMN OM_ORDER_HEADERS.order_number IS 'Format: YYMMDD + 3-digit sequence (e.g., 251006001)';

-- OM_ORDER_LINES: Order Line Items
CREATE TABLE OM_ORDER_LINES (
    line_id        NUMBER(10)    DEFAULT OM_ORDER_LINES_SEQ.NEXTVAL PRIMARY KEY,
    header_id      NUMBER(10)    NOT NULL,
    line_number    NUMBER(10)    NOT NULL,
    creation_date  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    item_id        NUMBER(10)    NOT NULL,
    quantity       NUMBER(10)    NOT NULL,
    cost_per_item  NUMBER(10,2)  NOT NULL,
    total_cost     NUMBER(10,2)  DEFAULT 0.00,
    is_paid        NUMBER(1)     DEFAULT 0,
    is_served      NUMBER(1)     DEFAULT 0,
    served_at      TIMESTAMP,
    served_by      VARCHAR2(255),
    kitchen_note   VARCHAR2(500),                          -- NEW: special instructions
    CONSTRAINT fk_order_line_header FOREIGN KEY (header_id) REFERENCES OM_ORDER_HEADERS(header_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_line_item   FOREIGN KEY (item_id) REFERENCES FOO_FOOD_MST(item_id),
    CONSTRAINT uq_header_line       UNIQUE (header_id, line_number),
    CONSTRAINT chk_line_qty         CHECK (quantity > 0),
    CONSTRAINT chk_line_cost        CHECK (cost_per_item > 0),
    CONSTRAINT chk_line_paid        CHECK (is_paid IN (0,1)),
    CONSTRAINT chk_line_served      CHECK (is_served IN (0,1))
);
--------------------------------------------------------------------------------
-- 3: triggers
-- DEPENDS ON- 2: tables
--------------------------------------------------------------------------------

-- Generate order_number (YYMMDD + 3-digit daily sequence)
CREATE OR REPLACE TRIGGER OM_GENERATE_ORDER_NUMBER_TRG
    BEFORE INSERT ON OM_ORDER_HEADERS
    FOR EACH ROW
DECLARE
    v_date_prefix   VARCHAR2(6);
    v_sequence_num  NUMBER;
    v_new_order_no  NUMBER(18);
BEGIN
    v_date_prefix := TO_CHAR(SYSTIMESTAMP, 'YYMMDD');

    SELECT NVL(MAX(TO_NUMBER(SUBSTR(TO_CHAR(order_number), 7))), 0) + 1
      INTO v_sequence_num
      FROM OM_ORDER_HEADERS
     WHERE TO_CHAR(creation_date, 'YYMMDD') = v_date_prefix;

    IF v_sequence_num > 999 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Daily order limit (999) exceeded for date ' || v_date_prefix);
    END IF;

    v_new_order_no := TO_NUMBER(v_date_prefix || LPAD(v_sequence_num, 3, '0'));
    :NEW.order_number := v_new_order_no;
END;
/

-- Auto-increment line_number per header_id
CREATE OR REPLACE TRIGGER OM_GENERATE_LINE_NUMBER_TRG
    BEFORE INSERT ON OM_ORDER_LINES
    FOR EACH ROW
    WHEN (NEW.line_number IS NULL)
DECLARE
    v_next_line NUMBER;
BEGIN
    SELECT NVL(MAX(line_number), 0) + 1
      INTO v_next_line
      FROM OM_ORDER_LINES
     WHERE header_id = :NEW.header_id;

    :NEW.line_number := v_next_line;
END;
/

-- Calculate line total cost
CREATE OR REPLACE TRIGGER OM_CALCULATE_LINE_TOTAL_TRG
    BEFORE INSERT OR UPDATE ON OM_ORDER_LINES
    FOR EACH ROW
BEGIN
    :NEW.total_cost := :NEW.quantity * :NEW.cost_per_item;
END;
/

-- Validate order can only be marked fully paid if all lines are paid
CREATE OR REPLACE TRIGGER OM_VALIDATE_ORDER_PAYMENT_TRG
    BEFORE UPDATE ON OM_ORDER_HEADERS
    FOR EACH ROW
    WHEN (NEW.is_paid_full = 1 AND OLD.is_paid_full = 0)
DECLARE
    v_unpaid_lines NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_unpaid_lines
      FROM OM_ORDER_LINES
     WHERE header_id = :NEW.header_id AND is_paid = 0;

    IF v_unpaid_lines > 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'Cannot mark order as fully paid: ' || v_unpaid_lines || ' unpaid line(s) exist');
    END IF;
END;
/
--------------------------------------------------------------------------------
-- 4: views
-- DEPENDS ON- 02: tables, FOO module, CUST module
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW OM_PENDING_ORDERS_V AS
SELECT oh.header_id, oh.order_number, oh.creation_date, oh.table_no,
       NVL(c.name, 'Walk-in Customer') AS customer_name,
       fm.item_code, fm.item_number, fm.item_description,
       ol.line_number, ol.quantity, ol.line_id, ol.total_cost,
       oh.is_paid_full, oh.is_deferred
  FROM OM_ORDER_LINES ol, OM_ORDER_HEADERS oh, FOO_FOOD_MST fm, CUST_PERSON_ACC c
  WHERE ol.header_id = oh.header_id
   AND ol.item_id = fm.item_id
   AND oh.customer_id = c.customer_id(+)
   AND ol.is_served = 0
 ORDER BY oh.creation_date, ol.line_number;

CREATE OR REPLACE VIEW CUST_DEFERRED_ORDERS_V AS
SELECT oh.header_id, oh.order_number, oh.creation_date, c.name AS customer_name,
       oh.total_due
  FROM OM_ORDER_HEADERS oh, CUST_PERSON_ACC c 
  WHERE oh.customer_id = c.customer_id
   AND oh.is_paid_full = 0 AND oh.is_deferred = 1
 ORDER BY oh.creation_date;

CREATE OR REPLACE VIEW OM_TODAY_ORDER_SUMMARY_V AS
SELECT COUNT(*)                                   AS today_orders,
       NVL(SUM(CASE WHEN is_paid_full = 1 THEN total_due END), 0) AS today_revenue,
       SUM(CASE WHEN is_paid_full = 0 THEN 1 ELSE 0 END)          AS unpaid_orders
  FROM OM_ORDER_HEADERS
 WHERE TRUNC(creation_date) = TRUNC(SYSDATE);
--------------------------------------------------------------------------------
-- 5: sample data
-- DEPENDS ON- 2:tables, 3: triggers, FOO + CUST sample data loaded
--------------------------------------------------------------------------------

-- Walk-in, fully paid order (no customer)
INSERT INTO OM_ORDER_HEADERS (who_gave_order, is_paid_full, is_deferred, is_known_customer, table_no, order_status)
VALUES ('Cashier1', 1, 0, 0, 'Parcel', 'COMPLETED');

INSERT INTO OM_ORDER_LINES (header_id, item_id, quantity, cost_per_item, is_paid, is_served)
SELECT (SELECT MAX(header_id) FROM OM_ORDER_HEADERS), item_id, 2, 40.00, 1, 1
  FROM FOO_FOOD_MST WHERE item_code = 'B02';

-- Known customer, deferred (unpaid) order
INSERT INTO OM_ORDER_HEADERS (who_gave_order, is_paid_full, is_deferred, is_known_customer, customer_id, table_no, order_status)
SELECT 'Cashier2', 0, 1, 1, customer_id, 'Table 4', 'PENDING'
  FROM CUST_PERSON_ACC WHERE customer_number = 'CUST001';

INSERT INTO OM_ORDER_LINES (header_id, item_id, quantity, cost_per_item, is_paid, is_served)
SELECT (SELECT MAX(header_id) FROM OM_ORDER_HEADERS), item_id, 1, 180.00, 0, 0
  FROM FOO_FOOD_MST WHERE item_code = 'L05';

COMMIT;